[profile.default]
src = "src"
out = "out"
test = "test"
script = "script"
libs = ["lib"]
auto_detect_remappings = false
sender = "0x0f14341A7f464320319025540E8Fe48Ad0fe5aec"
evm_version = "london"
optimizer = true
optimizer_runs = 999999
bytecode_hash = "ipfs"
cbor_metadata = true
extra_output = ["devdoc", "userdoc", "metadata", "storageLayout"]

fs_permissions = [
  { "access" = "read-write", "path" = "./script/output/"},
  { "access" = "read-write", "path" = "./deployments/" },
  { "access" = "read", "path" = "./script/input/"},
  { "access" = "read", "path" = "./broadcast/" },
  { "access" = "read", "path" = "./out/" },
]

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
multiline_func_header = "attributes_first"
quote_style = "double"
number_underscore = "preserve"
single_line_statement_blocks = "preserve"
override_spacing = false
wrap_comments = false
ignore = []
contract_new_lines = false

[rpc_endpoints]
arbitrum-goerli = "https://goerli-rollup.arbitrum.io/rpc"
arbitrum-sepolia = "https://sepolia-rollup.arbitrum.io/rpc"
pangolin = "https://pangolin-rpc.darwinia.network"
crab = "https://crab-rpc.darwinia.network"
darwinia = "https://rpc.darwinia.network"
arbitrum = "https://arb1.arbitrum.io/rpc"
sepolia = "https://sepolia.infura.io/v3/${INFURA_KEY}"

[etherscan]
arbitrum = { key = "${ETHERSCAN_ARBITRUM_KEY}" }
arbitrum-goerli = { key = "${ETHERSCAN_ARBITRUM_KEY}" }
arbitrum-sepolia = { key = "${ETHERSCAN_ARBITRUM_KEY}" }
darwinia = { key = "${ETHERSCAN_DARWINIA_KEY}", url = "https://darwinia.api.subscan.io/api/scan/evm/contract/verifysource" }
pangolin = { key = "${ETHERSCAN_DARWINIA_KEY}", url = "https://pangolin.api.subscan.io/api/scan/evm/contract/verifysource" }
crab = { key = "${ETHERSCAN_DARWINIA_KEY}", url = "https://crab.api.subscan.io/api/scan/evm/contract/verifysource" }
